#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DelegadoDeCampo.Resource", IsApplication=true)]

namespace DelegadoDeCampo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int boton_azul = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int campo_de_texto = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Delegado = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int encabezado = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int fondo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int mini_fondo = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060014
			public const int btnAmarillaA = 2131099668;
			
			// aapt resource value: 0x7f060019
			public const int btnAmarillaB = 2131099673;
			
			// aapt resource value: 0x7f06001f
			public const int btnAtras = 2131099679;
			
			// aapt resource value: 0x7f06000a
			public const int btnCerrarSesion = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int btnCerrarSesionIP = 2131099649;
			
			// aapt resource value: 0x7f06001b
			public const int btnCerrarSesionJ = 2131099675;
			
			// aapt resource value: 0x7f060020
			public const int btnCerrarSesionT = 2131099680;
			
			// aapt resource value: 0x7f06000d
			public const int btnFinPartido = 2131099661;
			
			// aapt resource value: 0x7f060013
			public const int btnGolA = 2131099667;
			
			// aapt resource value: 0x7f060018
			public const int btnGolB = 2131099672;
			
			// aapt resource value: 0x7f060003
			public const int btnIniciarPartido = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int btnLogin = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int btnResultadosParciales = 2131099660;
			
			// aapt resource value: 0x7f060015
			public const int btnRojaA = 2131099669;
			
			// aapt resource value: 0x7f06001a
			public const int btnRojaB = 2131099674;
			
			// aapt resource value: 0x7f060022
			public const int btnSeleccionarTiempo = 2131099682;
			
			// aapt resource value: 0x7f060000
			public const int glCerrarSesionEstadoPartido = 2131099648;
			
			// aapt resource value: 0x7f060012
			public const int glEquipoA = 2131099666;
			
			// aapt resource value: 0x7f060017
			public const int glEquipoB = 2131099671;
			
			// aapt resource value: 0x7f06000e
			public const int glPuntuacion = 2131099662;
			
			// aapt resource value: 0x7f060009
			public const int login_error = 2131099657;
			
			// aapt resource value: 0x7f06001e
			public const int lvJugadores = 2131099678;
			
			// aapt resource value: 0x7f060023
			public const int npMinutoDecena = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int npMinutoUnidad = 2131099684;
			
			// aapt resource value: 0x7f060011
			public const int txtEquipoA = 2131099665;
			
			// aapt resource value: 0x7f060016
			public const int txtEquipoB = 2131099670;
			
			// aapt resource value: 0x7f06000b
			public const int txtEstadoPartido = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int txtInfo = 2131099652;
			
			// aapt resource value: 0x7f06001c
			public const int txtListadoJugadores = 2131099676;
			
			// aapt resource value: 0x7f060007
			public const int txtPass = 2131099655;
			
			// aapt resource value: 0x7f06000f
			public const int txtPuntuacionEquipoA = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int txtPuntuacionEquipoB = 2131099664;
			
			// aapt resource value: 0x7f06001d
			public const int txtSeleccionJugador = 2131099677;
			
			// aapt resource value: 0x7f060021
			public const int txtSeleccionTiempo = 2131099681;
			
			// aapt resource value: 0x7f060002
			public const int txtSesionIniciada = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int txtUserName = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int txtWelcome = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int IuInicioPartido = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int IuInicioSesion = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int IuMenuPrincipal = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int IuSeleccionJugador = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int IuSeleccionTiempo = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int texto_boton = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
